local t = require "testlib"

local function read_file(path)
  local handle = assert(io.open(path, "rb"))
  local value = assert(handle:read("*a"))
  handle:close()
  return value
end

t.test("core endpoints are POST-only and size limited", function()
  local source = read_file("luasrc/controller/xc.lua")
  t.contains(source, 'post_entry({ "admin", "services", "xc", "core-upload" }, "action_core_upload")')
  t.contains(source, 'post_entry({ "admin", "services", "xc", "core-activate" }, "action_core_activate")')
  t.contains(source, 'post_entry({ "admin", "services", "xc", "core-rollback" }, "action_core_rollback")')
  t.contains(source, 'post_entry({ "admin", "services", "xc", "core-delete" }, "action_core_delete")')
  t.contains(source, 'entry({ "admin", "services", "xc", "core-resource-update-status" }, action_target("action_core_resource_update_status"))')
  t.contains(source, "local function require_post(maximum)")
  t.contains(source, "CORE_UPLOAD_MAX")
end)

t.test("core resource updates are fixed-source POST actions", function()
  local source = read_file("luasrc/controller/xc.lua")
  t.contains(source, 'local assetmanager_module = require "xc.assetmanager"')
  t.contains(source, 'local assetjob_module = require "xc.assetjob"')
  t.contains(source, 'post_entry({ "admin", "services", "xc", "core-resource-update" }, "action_core_resource_update")')
  t.contains(source, 'post_entry({ "admin", "services", "xc", "core-resource-rollback" }, "action_core_resource_rollback")')
  t.contains(source, 'post_entry({ "admin", "services", "xc", "core-resource-cancel" }, "action_core_resource_cancel")')
  t.contains(source, 'entry({ "admin", "services", "xc", "core-resource-check" }, action_target("action_core_resource_check"))')
  t.contains(source, 'assetjob_module.new')
  t.contains(source, 'asset_job.start, asset_job, kind, source')
  t.contains(source, 'asset_job.status, asset_job')
  t.contains(source, 'asset_job.cancel, asset_job, job_id')
  t.contains(source, "assetmanager_module.new")
  t.contains(source, "status.resources")
  t.contains(source, "manager:rollback(kind)")
  t.contains(source, "manager.check_update, manager, kind, source")
  t.contains(source, 'asset_check_failed = 502')
  t.contains(source, 'post_entry({ "admin", "services", "xc", "asset-proxy-apply" }, "action_asset_proxy_apply")')
  t.contains(source, "manager.apply_proxy, manager, values")
  t.contains(source, 'asset_proxy_address_required = 400')
  t.contains(source, 'asset_proxy_port_invalid = 400')
  t.contains(source, 'asset_proxy_applied')
  t.eq(source:find('http.formvalue("url")', 1, true), nil)
end)

t.test("core upload only submits the binary field", function()
  local view = read_file("luasrc/view/xc/core.htm")
  t.contains(view, 'form.append("core_file"')
  t.eq(view:find('form.append("sha256"', 1, true), nil)
  t.eq(view:find('form.append("note"', 1, true), nil)
  t.contains(view, 'data-core-token="<%=token%>"')
  local controller = read_file("luasrc/controller/xc.lua")
  t.eq(controller:find('http.formvalue("sha256")', 1, true), nil)
  t.eq(controller:find('http.formvalue("note")', 1, true), nil)
end)

t.test("core upload validates the automatically hashed binary without user metadata", function()
  local source = read_file("luasrc/controller/xc.lua")
  t.contains(source, "local form_ok = pcall(function()")
  t.contains(source, "core_instance.validate, core_instance, upload.path")
  t.eq(source:find("file_value", 1, true), nil)
end)

t.test("core upload accepts LuCI field-name callback strings", function()
  local source = read_file("luasrc/controller/xc.lua")
  t.contains(source, "local field_name = type(field) == \"table\" and field.name or field")
  t.contains(source, "if field_name ~= \"core_file\" then return end")
end)

t.test("core page validates rendered values before injecting into the DOM", function()
  local view = read_file("luasrc/view/xc/core.htm")
  t.contains(view, "safeId")
  t.contains(view, "safeVersion")
  t.contains(view, "safeArch")
  t.contains(view, "safeHash")
  t.contains(view, "textContent")
end)

t.test("controller core status triggers pending transaction recovery first", function()
  local source = read_file("luasrc/controller/xc.lua")
  t.contains(source, "core_instance.recover_pending")
  t.contains(source, "core_instance.status")
  t.contains(source, "core_recovery_failed")
end)

t.test("controller core status preserves recovery details", function()
  local source = read_file("luasrc/controller/xc.lua")
  t.contains(source, "core_failure_response(recovery_failure.code or \"core_recovery_required\", recovery_failure)")
  t.contains(source, 'core_event(runtime_instance, "core recovery", recovered)')
  t.contains(source, 'core_failure_response(status_failure.code or "core_recovery_required", status_failure)')
end)

t.test("controller records core lifecycle operations without secrets", function()
  local source = read_file("luasrc/controller/xc.lua")
  t.contains(source, 'local function core_event(runtime_instance, message, value)')
  t.contains(source, 'core_event(runtime_instance, "core upload completed", installed)')
  t.contains(source, 'core_result(runtime_instance, value, "core activation")')
  t.contains(source, 'core_result(runtime_instance, value, "core rollback")')
  t.contains(source, 'core_result(runtime_instance, value, "core deletion")')
  t.eq(source:find('raw_outbound', 1, true), nil)
  t.eq(source:find('share_link', 1, true), nil)
end)

t.test("controller logs a safe uploaded core version summary", function()
  local source = read_file("luasrc/controller/xc.lua")
  t.contains(source, 'type(value.version) == "table"')
  t.contains(source, 'fields.id = value.version.id')
  t.contains(source, 'fields.arch = value.version.arch')
  t.contains(source, 'fields.size = math.floor(value.version.size)')
  t.contains(source, 'fields.sha256 = value.version.sha256:sub(1, 16):lower()')
end)

t.test("controller core action exceptions preserve recovery details", function()
  local source = read_file("luasrc/controller/xc.lua")
  t.contains(source, 'local fallback = { ok = false, code = "core_recovery_required", recovery_required = true }')
  t.contains(source, 'core_failure_response(value.code or "core_activate_failed", value)')
  t.contains(source, 'core_event(runtime_instance, "core activation", value)')
  t.contains(source, 'core_event(runtime_instance, "core rollback", value)')
  t.contains(source, 'core_event(runtime_instance, "core deletion", value)')
end)

t.test("controller core status exceptions preserve recovery details", function()
  local source = read_file("luasrc/controller/xc.lua")
  t.contains(source, 'core_event(runtime_instance, "core recovery", recovery_failure)')
  t.contains(source, 'core_failure_response(recovery_failure.code or "core_recovery_required", recovery_failure)')
  t.contains(source, 'core_event(runtime_instance, "core status", status_failure)')
  t.contains(source, 'core_failure_response(status_failure.code or "core_recovery_required", status_failure)')
end)

t.test("controller preserves safe recovery fields in core failures", function()
  local source = read_file("luasrc/controller/xc.lua")
  t.contains(source, "local function core_failure_response(code, value)")
  t.contains(source, "payload.recovery_required = true")
  t.contains(source, 'for _, key in ipairs({ "current", "previous", "failed_target" }) do')
end)

return true
