#!/bin/sh

[ "$INTERFACE" = "lan" ] || [ "$INTERFACE" = "wan" ] || exit 0
[ "$ACTION" = "ifup" ] || [ "$ACTION" = "ifupdate" ] || exit 0
[ "$(uci -q get xc.main.enabled)" = "1" ] || exit 0
/etc/init.d/xc reload
